#+TITLE: Telegram Desktop Themes
#+DESCRIPTION: Telegram Desktop Themes - 20+ themes
#+SETUPFILE:  https://luispengler.github.io/telegram-desktop-themes/org-html-themes/org/theme-bigblow.setup
#+OPTIONS: num:nil ^:{} toc:1

+ A collection of my own telegram themes for telegram desktop!

+ These themes were generated using a tool called [[https://github.com/agnipau/telegram-palette-gen][telegram-palette-gen]]

+ PS: The only difference between normal version and blured version is that in the blured one the wallpaper has a blur effect.

* Abstract Cabum!
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: -50px;margin-right: auto;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148379923-515c9940-4263-409c-8581-f8682c633a59.png

Follow [[https://t.me/addtheme/r6HDv5MEEXlO2hON][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: -50px;margin-right: auto;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879103-0de64fcb-58ad-402c-a6d2-5225b0f0daa5.png

Follow [[https://t.me/addtheme/pNBeYhfNgBvi80nl][this link]] to apply this theme to your telegram.

* Canon Lens
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148380211-ffda3ba1-a39c-4626-b43b-70fe04314c2c.png

Follow [[https://t.me/addtheme/fdTOwJHr3VUqMCEF][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148066037-4e85726b-3b20-4011-8cca-2a8a67bf2ffc.png

Follow [[https://t.me/addtheme/Pe6hGaC2zBA3YPE7][this link]] to apply this theme to your telegram.

* Cyberpunk 2077 road
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148387160-53e1906a-ccf7-4680-b26a-bff010e775a0.png

Follow [[https://t.me/addtheme/XajySuay8z2jSlUB][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148387352-870e26f9-088b-4c2a-89c6-0766a7d5757b.png

Follow [[https://t.me/addtheme/AuuQvFbMFOyHIklE][this link]] to apply this theme to your telegram.

* Gears keep movin'
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148378765-08899cd8-258d-47ee-9250-ae522d45eac5.png

Follow [[https://t.me/addtheme/y4qBtRJEGCZCBCVI][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879130-6930ce57-9868-49e9-9b05-b6965841cb34.png

Follow [[https://t.me/addtheme/FsLlCXCzWzO2NMJh][this link]] to apply this theme to your telegram.

* Genshin Impact Yae Miko
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148108989-9173d80b-7298-48ef-b6bf-b3f6180f0ff8.png

Follow [[https://t.me/addtheme/HbAqmOzWUSGZ0fNV][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148109309-f9cb2cd7-8452-42d7-8e54-69780bbdfdd5.png

Follow [[https://t.me/addtheme/tfWiqpJ0DxTExDKB][this link]] to apply this theme to your telegram.

* Harry Potter 1
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148384250-9ab8a69e-95e2-4622-9de0-38d13899c5a4.png

Follow [[https://t.me/addtheme/f7Q2kBGtZRB1XzTt][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147886074-eb2451fd-6b16-47b2-863f-57127c65f30c.png

Follow [[https://t.me/addtheme/VaJX1eneJZcFykI6][this link]] to apply this theme to your telegram.

* Majestic Spot
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148233265-9f1b1ae2-e333-4c0d-a271-6520cbbfc426.png

Follow [[https://t.me/addtheme/CWuPV15rD4AAyPAu][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148233336-f2ab86e6-48f3-407d-a743-fabb1d0c405c.png

Follow [[https://t.me/addtheme/LRO0RjFJTwrEaJb7][this link]] to apply this theme to your telegram.

* Purple Saturn
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/telegram-desktop-themes/tdesktop-palette/purple-saturn/ss.png

Follow [[https://t.me/addtheme/DmICQHEpcgU5vydP][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://luispengler.github.io/telegram-desktop-themes/tdesktop-palette/purple-saturn/ssb.png

Follow [[https://t.me/addtheme/YXLvPd4BMCVVj3Jv][this link]] to apply this theme to your telegram.

* Simple Saturn

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879176-44370e96-2ee6-4386-aa6b-16b8a387100a.png

Follow [[https://t.me/addtheme/xmkKIj6pjiFJju7K][this link]] to apply this theme to your telegram.

* Space ship art
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148384596-a85e64e2-d9bc-451f-8aae-d0b769d1efaa.png

Follow [[https://t.me/addtheme/Brhi4pUw1Id2FVJS][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879421-64cd3cab-be9c-437a-9872-3b782387a67a.png

Follow [[https://t.me/addtheme/FcfzJFZbrslWPFnH][this link]] to apply this theme to your telegram.

* Red Blossoms
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148558290-13720d8f-9e94-4dcd-8d40-b7c808cca7dd.png

Follow [[https://t.me/addtheme/ySD4YGRutpmgpFCM][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148558506-93b0f1c1-0e8b-4ca1-a0da-5ca38b1f735c.png

Follow [[https://t.me/addtheme/dy96SE8K8VfD6SRP][this link]] to apply this theme to your telegram.

* Spider main theme
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148384856-cd707add-7397-4ca0-83ad-7e3fbef38d08.png

Follow [[https://t.me/addtheme/CAnElsu44Bcof9sh][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879189-87185f1e-07ed-4322-8197-da21f1bfc625.png

Follow [[https://t.me/addtheme/L7Ib4C0kE5Z0nmqY][this link]] to apply this theme to your telegram.

* Star atlas craziness
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385145-6ebab3c8-c530-48f7-be26-2930d7a19d31.png

Follow [[https://t.me/addtheme/Ht1ibAnXFxd3fyq3][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147941767-30651568-4936-47a7-9c95-6e0d01ded2d6.png

Follow [[https://t.me/addtheme/mvBlrPOD0eJ702UF][this link]] to apply this theme to your telegram.

* Star atlas Pearce F4
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385376-b6a02e86-d6dc-4b13-bc60-fdb737d1006c.png

Follow [[https://t.me/addtheme/GFtnX20CSxeVsv7y][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147890795-5344c14f-f414-4b55-8267-07ca01d0558a.png

Follow [[https://t.me/addtheme/chFAe8GQj8IvTn4D][this link]] to apply this theme to your telegram.

* The last of Ellie
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385565-49c62877-d7bd-43bd-a272-e8a1e52bd8f1.png

Follow [[https://t.me/addtheme/QwHOYOAT02CCFwpj][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148076464-626900e6-e8b5-4b5f-82a3-05885af8a895.png

Follow [[https://t.me/addtheme/uYjIuDJecOlbD7Gt][this link]] to apply this theme to your telegram.

* Tree boy
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385565-49c62877-d7bd-43bd-a272-e8a1e52bd8f1.png

Follow [[https://t.me/addtheme/QwHOYOAT02CCFwpj][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148076464-626900e6-e8b5-4b5f-82a3-05885af8a895.png

Follow [[https://t.me/addtheme/uYjIuDJecOlbD7Gt][this link]] to apply this theme to your telegram.


* Virtual Reality

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147879200-9185e389-6961-4a50-ad94-065fde616925.png

Follow [[https://t.me/addtheme/m1jjJXpuV0hjKrqo][this link]] to apply this theme to your telegram.

* Yellow forest
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385758-ebfc9cef-f3d7-47d1-bf4a-4f58f9a286c9.png

Follow [[https://t.me/addtheme/zUjn8oFndBD9cC55][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148073784-3e818e96-6ee1-4be4-9924-c0f2967e8e85.png

Follow [[https://t.me/addtheme/YIogUS7M9wJaaLLu][this link]] to apply this theme to your telegram.

* Your name 1
** Normal Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/148385972-04580e8d-54ce-4b3e-ae8a-3d466e15ad0e.png

Follow [[https://t.me/addtheme/mawGZD5IlnuwqfEE][this link]] to apply this theme to your telegram.

** Blured Version

#+ATTR_HTML: alt: waterwave :title Double-slit :style margin-left: auto;margin-right: auto;background-color: mintcream;display: block;width: 100%;
https://user-images.githubusercontent.com/71613402/147890659-c6522b4c-99ef-4896-9b24-78a7ce5a51d9.png

Follow [[https://t.me/addtheme/p7Chaq7LnarHLNQS][this link]] to apply this theme to your telegram.
